apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers
  name: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - image:  store/customers
        name: app

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers
  name: customers-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: customers
    
